  name: Enigma_LifeSteal
  main: org.enigma.Enigma
  version: DEV-01
  authors:
    - Woahhs
    - InspectMC
  description: All in one Lifesteal Survival Core. This plugin is made with the best optimization tweaks, with amazing exclusive features!
