  name: OneLife
  main: org.enigma.onelife.OneLife
  version: DEV-01
  authors:
    - Woahhs
  description: All in one OneLife Survival Core. This plugin is made with the best optimization tweaks, with amazing exclusive features!
